# infra/local/packer/ubuntu-siem.pkr.hcl
#
# Builds siem01 from Ubuntu Server 22.04 LTS's official ARM64 cloud image
# (a pre-installed qcow2, not an ISO installer) plus a NoCloud cloud-init
# seed — the standard, low-risk way to automate an Ubuntu build, and
# notably simpler/more reliable than the Debian-installer preseed approach
# used for attacker01 (see kali-attacker.pkr.hcl) since there's no
# installer UI automation involved at all.

packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1.1"
    }
  }
}

variable "base_image_url" {
  type        = string
  default     = "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  description = "Ubuntu 22.04 LTS ARM64 cloud image. Canonical's URL scheme has been stable for years, but re-verify the checksum below against https://cloud-images.ubuntu.com/releases/22.04/release/SHA256SUMS before relying on it."
}

variable "base_image_checksum" {
  type        = string
  description = "sha256:<hash> for base_image_url — fetch current value from the SHA256SUMS file at the URL above; no default, must be supplied."
}

variable "admin_username" {
  type    = string
  default = "labadmin"
}

variable "efi_firmware_code" {
  type        = string
  default     = "/opt/homebrew/share/qemu/edk2-aarch64-code.fd"
  description = "UEFI CODE firmware for qemu-system-aarch64. infra/local/build-linux.sh derives and overrides this from wherever qemu-system-aarch64 actually resolves on PATH — see kali-attacker.pkr.hcl's efi_firmware_code variable for the full explanation of why this uses Packer's efi_boot mechanism rather than the legacy firmware/-bios field. The Homebrew-specific default here is only a fallback for direct `packer build` invocations."
}

variable "efi_firmware_vars" {
  type        = string
  default     = "/opt/homebrew/share/qemu/edk2-arm-vars.fd"
  description = "UEFI VARS template pairing efi_firmware_code — edk2-arm-vars.fd, shared across 32-bit ARM and aarch64 (QEMU does not ship a separate edk2-aarch64-vars.fd)."
}

variable "output_directory" {
  type    = string
  default = "infra/local/build/images/siem01"
}

variable "nocloud_iso" {
  type        = string
  description = "Path to a pre-built NoCloud (cidata) seed ISO — generated by infra/local/generate_nocloud_iso.py, NOT Packer's own cd_files/cd_label mechanism. See that script's docstring: Packer's SDK unconditionally builds cd_files ISOs via `hdiutil makehybrid -hfs`, producing an HFS+-wrapped image that cloud-init's guest kernel can't read as plain ISO9660, so the NoCloud seed silently never gets found (upstream bug, hashicorp/packer-plugin-qemu#133). No default — build-linux.sh always supplies this."
}

source "qemu" "ubuntu_siem" {
  iso_url      = var.base_image_url
  iso_checksum = var.base_image_checksum
  # This is a pre-built cloud image, not an installer ISO — Packer's qemu
  # builder still calls the source file "iso_url" internally, but disk_image
  # tells it to boot the file directly as a disk rather than treating it as
  # installer media.
  disk_image       = true
  output_directory = var.output_directory
  vm_name          = "siem01.qcow2"
  format           = "qcow2"

  qemu_binary       = "qemu-system-aarch64"
  accelerator       = "hvf"
  machine_type      = "virt"
  efi_firmware_code = var.efi_firmware_code
  efi_firmware_vars = var.efi_firmware_vars
  cpu_model         = "host"

  cpus      = 2
  memory    = 4096
  disk_size = "40000M" # Elastic/Wazuh indices during scenario runs — see infra/azure/siem.tf history for the same sizing rationale (git log)

  net_device     = "virtio-net"
  disk_interface = "virtio"

  headless = true

  # Same visibility gap as kali-attacker.pkr.hcl's qemuargs comment: no
  # GPU device on aarch64 "virt" means VNC only ever shows QEMU's own
  # monitor, not cloud-init's boot log — a real serial log is the only
  # way to see what's actually happening. This build doesn't need the
  # GPU/USB-input devices kali-attacker.pkr.hcl needs (cloud-init is
  # driven entirely by the NoCloud seed + SSH, no keyboard interaction),
  # just the serial log for diagnosis.
  #
  # The NoCloud seed is attached here directly, NOT via cd_files/cd_label
  # — see the nocloud_iso variable's description for why.
  qemuargs = [
    ["-serial", "file:infra/local/build/siem01-serial.log"],
    ["-drive", "file=${var.nocloud_iso},media=cdrom"],
  ]

  communicator         = "ssh"
  ssh_username         = var.admin_username
  ssh_private_key_file = "infra/local/build/ssh/lab_ed25519"
  ssh_timeout          = "30m" # native arm64, no TCG emulation — should be fast

  shutdown_command = "sudo -S shutdown -P now"
}

build {
  sources = ["source.qemu.ubuntu_siem"]

  provisioner "shell" {
    inline = [
      "sudo apt-get update",
      "sudo apt-get install -y qemu-guest-agent",
      "sudo systemctl enable qemu-guest-agent"
    ]
  }
}
