# infra/local/packer/windows-server.pkr.hcl
#
# Builds a base Windows Server 2022 qcow2 image via QEMU's TCG (software)
# x86_64 emulation — this Mac is Apple Silicon with no hardware-acceleration
# path for an x86_64 guest, so the build is slow but genuine (see
# docs/adr/0004-revert-to-local-utm.md). Used for both dc01 and mem01 via
# separate `packer build -var vm_name=... -var-file=...` invocations — see
# infra/local/dc.pkrvars.hcl and infra/local/member.pkrvars.hcl.
#
# Network device is e1000 (Intel NIC, natively supported by Windows Server
# without extra drivers) rather than virtio, specifically to avoid needing
# a virtio driver ISO during unattended install — one less moving part.

packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1.1"
    }
    windows-update = {
      source  = "github.com/rgl/windows-update"
      version = "~> 0.16"
    }
  }
}

variable "vm_name" {
  type        = string
  description = "dc01 or mem01 — used for the output image filename and Autounattend ComputerName."
}

variable "iso_url" {
  type        = string
  description = "Local path (not a URL — see below) to the Windows Server 2022 evaluation ISO. Download from https://www.microsoft.com/evalcenter/download-windows-server-2022 — no default, must be supplied (see README.md Prerequisites). Must be a local path: qemuargs (below) attaches it directly via -drive, which needs a real filesystem path, not something QEMU can fetch itself. Packer's normal iso_url/iso_checksum download+cache step still runs and still verifies the checksum either way — it just also happens to already resolve local paths to themselves without re-downloading, which is what makes this work."
}

variable "iso_checksum" {
  type        = string
  description = "sha256:<hash> for iso_url. Get this from the same Evaluation Center download page — never skip verifying it."
}

variable "admin_password" {
  type      = string
  sensitive = true
}

variable "output_directory" {
  type    = string
  default = "infra/local/build/images"
}

variable "rendered_autounattend" {
  type        = string
  description = "Path to an Autounattend.xml with the real admin password already substituted in — generated by build.sh into infra/local/build/ (gitignored), NOT the tracked infra/local/packer/http-windows/Autounattend.xml itself. That file was previously mutated in place (rendered, then restored via a trap on script exit); an interrupted build (e.g. the VM killed directly rather than letting build.sh exit normally) could skip the restore step and leave a real plaintext password sitting in a tracked file — which is exactly what happened once this session (see BUILD_LOG.md session 4: a real password ended up committed and pushed before this was caught and fixed). Rendering to a gitignored path instead makes that failure mode structurally impossible rather than just unlikely."
}

variable "seed_iso" {
  type        = string
  description = "Path to a pre-built answer-file seed ISO (Autounattend.xml + bootstrap.ps1) — generated by infra/local/generate_windows_seed_iso.py, NOT Packer's own cd_files/cd_label mechanism. See infra/local/iso_builder.py's docstring: Packer's SDK unconditionally builds cd_files ISOs via `hdiutil makehybrid -hfs`, and on a real build, D:\\bootstrap.ps1 (delivered this way) never actually ran — WinRM stayed Negotiate-only forever, confirmed by probing its WWW-Authenticate header directly. No default — build.sh always supplies this."
}

source "qemu" "windows_server" {
  iso_url          = var.iso_url
  iso_checksum     = var.iso_checksum
  output_directory = "${var.output_directory}/${var.vm_name}"
  vm_name          = "${var.vm_name}.qcow2"
  format           = "qcow2"

  qemu_binary = "qemu-system-x86_64"
  accelerator = "tcg" # no HVF for a foreign-arch (x86_64) guest on Apple Silicon

  cpus      = 2
  memory    = 4096
  disk_size = "60000M"

  net_device     = "e1000"
  disk_interface = "ide"

  headless = true

  # NOT cd_files/cd_label — see the seed_iso variable's description for
  # why. Packer's arg-merging keys defaults by flag name (see
  # kali-attacker.pkr.hcl's qemuargs comment for the full explanation of
  # this same gotcha found first on that build): any -drive in qemuargs
  # drops ALL of Packer's own auto-generated -drive entries, not just
  # adds one more. So this replicates the main disk and the real Windows
  # install ISO (normally auto-generated from iso_url/disk_interface)
  # alongside the custom seed ISO, since adding any -drive of our own
  # makes us responsible for all of them.
  qemuargs = [
    ["-drive", "file=${var.output_directory}/${var.vm_name}/${var.vm_name}.qcow2,if=ide,cache=writeback,discard=ignore,format=qcow2"],
    ["-drive", "file=${var.iso_url},media=cdrom"],
    ["-drive", "file=${var.seed_iso},media=cdrom"],
  ]

  communicator   = "winrm"
  winrm_username = "labadmin"
  winrm_password = var.admin_password
  winrm_timeout  = "6h" # TCG-emulated Windows Server install is genuinely slow — see ADR 0004

  shutdown_command = "shutdown /s /t 10 /f /d p:4:1"
}

build {
  sources = ["source.qemu.windows_server"]

  provisioner "powershell" {
    inline = [
      "Set-ExecutionPolicy Unrestricted -Force",
      "winrm quickconfig -quiet",
      "Enable-PSRemoting -Force",
      "New-NetFirewallRule -Name WinRM-HostOnly -DisplayName 'WinRM (lab host-only)' -Protocol TCP -LocalPort 5985 -Action Allow"
    ]
  }

  provisioner "windows-update" {}
}
