from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.config import settings


def test_coverage_endpoint_returns_real_committed_matrix(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    # Uses the real detections/coverage_matrix.json committed to the repo
    # (generated by `make detections-test`) rather than a fixture — proves
    # the endpoint actually reads what's on disk.
    response = client.get("/coverage", headers=auth_headers)
    assert response.status_code == 200
    body = response.json()
    assert body["summary"]["total_techniques"] == 6
    assert body["summary"]["covered"] == 6


def test_coverage_endpoint_404s_when_matrix_missing(
    client: TestClient,
    auth_headers: dict[str, str],
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(settings, "coverage_matrix_file", tmp_path / "does-not-exist.json")
    response = client.get("/coverage", headers=auth_headers)
    assert response.status_code == 404


def test_coverage_endpoint_requires_auth(client: TestClient) -> None:
    response = client.get("/coverage")
    assert response.status_code == 401
