from __future__ import annotations

from pathlib import Path

import pytest
from attack.techniques import TECHNIQUES
from fastapi.testclient import TestClient

from app.config import settings


def test_coverage_endpoint_returns_real_committed_matrix(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    # Uses the real detections/coverage_matrix.json committed to the repo
    # (generated by `make detections-test`) rather than a fixture — proves
    # the endpoint actually reads what's on disk. Compares against the
    # real technique registry rather than a hardcoded count, so this
    # doesn't go stale the next time a technique is added (as a hardcoded
    # "== 6" did when misconfigs 6/7 brought the count to 8).
    response = client.get("/coverage", headers=auth_headers)
    assert response.status_code == 200
    body = response.json()
    assert body["summary"]["total_techniques"] == len(TECHNIQUES)
    assert body["summary"]["covered"] == len(TECHNIQUES)


def test_coverage_endpoint_404s_when_matrix_missing(
    client: TestClient,
    auth_headers: dict[str, str],
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(settings, "coverage_matrix_file", tmp_path / "does-not-exist.json")
    response = client.get("/coverage", headers=auth_headers)
    assert response.status_code == 404


def test_coverage_endpoint_requires_auth(client: TestClient) -> None:
    response = client.get("/coverage")
    assert response.status_code == 401
