"""Serves detections/coverage_matrix.json — generated by `make
detections-test`, not by this endpoint. Feeds the (not yet built)
frontend heatmap. Deliberately reads the file rather than importing
detections.coverage/re-running the test suite on every request — this
endpoint should be cheap, and regenerating coverage is a build-time
concern (make detections-test / CI), not a request-time one.
"""

from __future__ import annotations

import json
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status

from app.auth import get_current_user
from app.config import settings
from app.models import User

router = APIRouter(prefix="/coverage", tags=["coverage"])


@router.get("")
def get_coverage(_current_user: Annotated[User, Depends(get_current_user)]) -> dict[str, Any]:
    if not settings.coverage_matrix_file.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"{settings.coverage_matrix_file} not found — run "
                "`make detections-test` to generate it."
            ),
        )
    data: dict[str, Any] = json.loads(settings.coverage_matrix_file.read_text())
    return data
